--- 
box: node:8.9.4
command-timeout: 30
echo: 
  steps: 
    - 
      script: 
        name: "echo TEST var"
        code: |
          env
    - script:
        name: "get TEST VAR"
        code: |
          ls -laR /
build:
  steps:
    - script:
            name: "test"
            code: |
              sleep 10

secondBuild:
  steps:
    - npm-install

dockerBuild:
  steps:
    - script:
        name: "build dockerfile"
        code: |
          bash -c '$COMMAND
                   $COMMAND1
                   $COMMAND2
                   $COMMAND3
                   $COMMAND4
                   $COMMAND5
                   $COMMAND6
                   $COMMAND7
                   $COMMAND8
                   $COMMAND9
                   $COMMAND10
                   $COMMAND11
                   $COMMAND12
                   $COMMAND13
          '

noCacheInstall:
  steps:
    - script:
        name: "npm install"
        code: |
          npm install
trigger:
  steps:
    - petrica/trigger-build:
          pipeline-id: 59fca3d827e1a90100bb7422
          token: cce6179937475369a260d0b6ff5785343ba001a5ba29aa91409ec8767cc9cad7
          branch: master
          message: custom trigger message
  steps:
    - add-ssh-key:
      keyname: WERCKER

    -
      script:
        name: "git"
        code: |
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          git config --global user.email "gapostolov333@gmail.com"
          git config --global user.name "Georgi"
          git clone  git@github.com:exploitx3/CoursesManagementApp-NodeJS-Express.git tmp
          cd tmp
          git pull
          sed -i "s/([A-Z])\w+/TT/g" t.txt
          git status
          git add .
          git commit -m " auto commit"
          git push
          git status

    - script:
        name: "save env vars in file"
        code: |
          echo $TEST > /pipeline/source/new.txt
          echo $TEST > /t.txt
    -
      script:
        code: |
          ls -laR /
        name: env

follow:
  steps:
    - script:
            name: "trigger"
            code: |
              node create-release-branches.js
